#!/bin/sh

set -e -x

GATEWAY=${GATEWAY:-99.99.135.99}
REMOTEHOST=${REMOTEHOST:-99.99.135.123}
MNTSRC=/home/user
MNTTGT=~/mnt/vps
USER=user
LOCALLISTENPORT=5901
REMOTEPORT=5901


mkdir -p $MNTTGT
sshfs $USER@$GATEWAY:$MNTSRC $MNTTGT
ssh -X -L $LOCALLISTENPORT:$REMOTEHOST:$REMOTEPORT $USER@$GATEWAY

